### ISSUE TITLE
Lack of information about pointnet2_ops

### ISSUE THREAD

**Issue by RyoseiKanekoTUS** [sectionZ6/UniDoorManip#2]
Hi, thankyou for sharing your door-manipulation repo.
I followed the instructions in the README to set up your simulation environment and tried running the scripts in scripts/{all_your_shell_scripts}.sh. However, I encountered an error stating that the pointnet2_ops package could not be imported, which prevented the scripts from running like

 ```
 File "/path/to/UniDoorManip/Simulation/env/franka_slider_safe.py", line 12, in <module>
    from pointnet2_ops import pointnet2_utils
ModuleNotFoundError: No module named 'pointnet2_ops'
```

Could you please provide additional information on where to install the pointnet2_ops package from, or any other relevant setup details? Thank you!

**Comment by Student-of-Holmes** [comment]
This is a pakage provided by PointNet++. You can install the Pytorch version PointNet++ in the conda environment by following theses command:
  ```shell
     git clone --recursive https://github.com/erikwijmans/Pointnet2_PyTorch
     cd Pointnet2_PyTorch
     pip install -r requirements.txt
     pip install -e .
  ```

**Comment by RyoseiKanekoTUS** [comment]
Thank you for your description with command @Student-of-Holmes 
I finally solved the ImportError. 
I'll continue to try your package !
