### ISSUE TITLE
Are the training code and dataset complete?

### ISSUE THREAD

**Issue by wanxidong** [sectionZ6/UniDoorManip#3]
Hello, thank you for sharing this project!

While using the repository, I noticed that some parts of the training code and dataset seem incomplete. Could you clarify if there is a complete version of the training code and dataset available? Additionally, is there any further documentation or explanation regarding the training process?

I would really appreciate your help! Thanks again for your great work.

**Comment by Student-of-Holmes** [comment]
Hello, thanks for your attention to our work. 
The training code and dataset are complete. We will modify the documents to make our code easier to use.

**Comment by wanxidong** [comment]
Thank you for your response and for clarifying that the documents will be updated to make the code easier to use. This update will be really helpful. 
Thanks again for your great work and support.
